// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVw2uuvKsIsqHH9loaTR2-nf_IqSTT6jw',
    appId: '1:300622168794:web:5d9d02569c8329717c9be3',
    messagingSenderId: '300622168794',
    projectId: 'invoice-gen-d5c86',
    authDomain: 'invoice-gen-d5c86.firebaseapp.com',
    storageBucket: 'invoice-gen-d5c86.firebasestorage.app',
    measurementId: 'G-RBG8HRC1CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUtqC4d6IWnY9sV8RQD4po33yqgg695x8',
    appId: '1:300622168794:android:898f7abb44dbb6a37c9be3',
    messagingSenderId: '300622168794',
    projectId: 'invoice-gen-d5c86',
    storageBucket: 'invoice-gen-d5c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2N4iht6_LtnqXgLm2A7Qz_ql2wOl5X70',
    appId: '1:300622168794:ios:71182546e63524917c9be3',
    messagingSenderId: '300622168794',
    projectId: 'invoice-gen-d5c86',
    storageBucket: 'invoice-gen-d5c86.firebasestorage.app',
    iosBundleId: 'com.invoicegenarator.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2N4iht6_LtnqXgLm2A7Qz_ql2wOl5X70',
    appId: '1:300622168794:ios:78b8f5404bbf17ef7c9be3',
    messagingSenderId: '300622168794',
    projectId: 'invoice-gen-d5c86',
    storageBucket: 'invoice-gen-d5c86.firebasestorage.app',
    iosBundleId: 'com.example.invoiceGenarator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVw2uuvKsIsqHH9loaTR2-nf_IqSTT6jw',
    appId: '1:300622168794:web:b8b53b13f892613f7c9be3',
    messagingSenderId: '300622168794',
    projectId: 'invoice-gen-d5c86',
    authDomain: 'invoice-gen-d5c86.firebaseapp.com',
    storageBucket: 'invoice-gen-d5c86.firebasestorage.app',
    measurementId: 'G-C616SXFG35',
  );
}
